apiVersion: v1
kind: Service
metadata:
  name: jobops
  labels:
    app.kubernetes.io/name: jobops
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jobops
    app.kubernetes.io/component: real-application-control-plane
  ports:
    - name: http
      port: 9000
      targetPort: http
      protocol: TCP
